version: "3"
networks:
    testing_net_automation:
      ipam:
        driver: default
        config:
          - subnet: 172.16.238.0/24

services:
  node_alice:
    image: mangatasolutions/mangata-node:${MANGATA_NODE_VERSION}
    volumes:
      - /home/goncer/projects/:/myapp
    container_name: alice
    entrypoint: ./node --alice --rpc-cors=all --collator --unsafe-ws-external --unsafe-rpc-external  --force-authoring --tmp --port 40333 --ws-port 8844 -- --execution wasm --chain /myapp/mangata_v4_chainspec.json --port 30343
    ports:
      - "40333:40333"
      - "8833:9933"
      - "8844:8844"
    networks:
        testing_net_automation:
            ipv4_address: 172.16.238.10
volumes:
  myapp:

