endpoint: wss://kusama-archive.mangata.online
# endpoint: ws://127.0.0.1:9946
mock-signature-host: true
db: ./mangata.db.sqlite
port: 9946

registered-types:
    types:
      ShufflingSeed:
        seed: 'H256'
        proof: 'H512'
      Header:
        parentHash: 'Hash'
        number: 'Compact<BlockNumber>'
        stateRoot: 'Hash'
        extrinsicsRoot: 'Hash'
        digest: 'Digest'
        seed: 'ShufflingSeed'
        count: 'BlockNumber'

import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  Tokens:
    Accounts:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - token: 0
        - free: '1000000000000000000000000' # 1M MG
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - token: 30
        - free: 1000e6 # 1K USDT

  Council:
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
  AssetRegistry:
    Metadata:
      -
        -
          - 100
        - decimals: 18
          symbol: vMOVR
          additional:
            xcm:
              feePerSecond: '2688000000000000000'
          location:
            V1:
              parents: 1
              interior:
                X2:
                  - Parachain: 2001
                  - GeneralKey: '0x010A'
      -
        -
          - 101
        - decimals: 18
          symbol: ZLK
          additional:
            xcm:
              feePerSecond: '80640000000000000000'
          location:
            V1:
              parents: 1
              interior:
                X2:
                  - Parachain: 2001
                  - GeneralKey: '0x0207'
      
    LocationToAssetId:
      -
        -
          - parents: 1
            interior:
              X2:
                - Parachain: 2001
                - GeneralKey: '0x0207'
        - 101