endpoint: wss://statemine-rpc.polkadot.io
mock-signature-host: true
db: ./statemine.db.sqlite
port: 9948

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - data:
            free: 1000000000000000 # 1K KSM
  Assets:
    Account:
      -
        -
          - 1984
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - balance: 1000000000 # 1K USDt
