on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Test code quality and run tests
    runs-on: ubuntu-latest
    env:
      API_URL: 'ws://172.16.238.10:9944'
      TEST_PALLET_ADDRESS: ${{ secrets.TEST_PALLET_ADDRESS }}
      TEST_SUDO_NAME: ${{ secrets.TEST_SUDO_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: tsc code quality check
        run: yarn tsc-lint
      - name: ESLint code quality check
        run: yarn eslint
      - name: Start node img.
        run: docker-compose up -d -f devops/docker-compose.yml
      - name: get docker ps
        run: docker ps
      - name: Run job
        run: yarn test-sequential-e2e
      
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
# tests are not ready to run in github.
# TODO: Build image, export pallet address and run yarn test-parallel && yarn test-sequential
#      - name: Run tests
#        run: CI=true yarn test
