name: e2e workflow

on:
  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:
      inputs:
        scriptName:
          description: 'Name of the script to run'
          required: false
          default: 'test-ui'
      # For manually trigger
 

jobs:
  test:
    name: Run UI tests
    runs-on: ubuntu-latest
    container:
      image: node:14.4
      options: --network-alias testHost
    env:
      API_URL: 'wss://staging.testnode.mangata.finance:9945'
      TEST_PALLET_ADDRESS: ${{ secrets.TEST_PALLET_ADDRESS }}
      TEST_SUDO_NAME: ${{ secrets.TEST_SUDO_NAME }}
      MNEMONIC_META: ${{ secrets.MNEMONIC_META }}
      MNEMONIC_POLK: ${{ secrets.MNEMONIC_POLK }}
      TEST_SCRIPT: 'test-sequential-e2e'
      NODE_ENV: test
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-chrome:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444

    steps:
      - name: Set variables
        run:  |
          echo "TEST_SCRIPT=${{ github.event.inputs.scriptName || env.TEST_SCRIPT }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Tsc code quality check
        run: yarn tsc-lint
      - name: ESLint code quality check
        run: yarn eslint
      - name: Docker ps
        run: docker ps
      - name: Run e2e tests
        run: yarn ${{ env.TEST_SCRIPT }}
      
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results

